site_name: pyinvoicer
nav:
  - Home: README.md
  - Contributing: contributing.md
theme:
  name: 'material'
repo_url: https://github.com/tai271828/pyinvoicer
remote_branch: gh-pages
remote_name: origin
